[tool.poetry]
name = "project1"
version = "0.1.0"
description = ""
authors = ["username"]

[tool.poetry.dependencies]
python = ">=3.8,<3.10"
jupyter = "*"
sklearn = "*"
matplotlib = "*"
pandas = "*"
seaborn = "*"
japanize-matplotlib = "*"
sentencepiece = "*"
protobuf = "*"
transformers = "*"
datasets = "*"
torch = "*"
numpy = "*"
jupyterlab = "*"
mecab-python3 = "*"
tensorflow = "^2.8.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
ipykernel = "^6.13.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
